use crate::diagnostic::Diagnostic;
use crate::diagnostic_severity::DiagnosticSeverity;
use crate::document::Document;
use crate::document_id::DocumentId;
use serde::Deserialize;

/// The target language for compilation
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
pub enum TargetLanguage {
    #[serde(rename = "ts")]
    Typescript,
    #[serde(rename = "rust")]
    Rust,
}

/// The contents of a `hop.toml` file.
#[derive(Debug, Clone)]
pub struct Config {
    document: Document,
}

impl Config {
    /// Wrap the contents of a `hop.toml` file. Parsing happens lazily in the accessors.
    pub fn new(document: Document) -> Self {
        Config { document }
    }

    fn parse<T: serde::de::DeserializeOwned>(&self) -> Result<T, Diagnostic> {
        toml::from_str(self.document.as_str()).map_err(|err| {
            Diagnostic {
                message: err.message().to_string(),
                // A zero-width span is kept as a position marker, toml reports
                // one for "expected X here" and for a missing top-level section.
                range: self.document.range(err.span().unwrap_or(0..0)),
                severity: DiagnosticSeverity::Error,
            }
        })
    }

    /// The CSS entrypoint.
    pub fn css_input_path(&self) -> Result<Option<DocumentId>, Diagnostic> {
        Ok(self.parse::<CssToml>()?.css.map(|css| css.input_path))
    }

    /// The JS/TS entrypoint.
    pub fn js_input_path(&self) -> Result<Option<DocumentId>, Diagnostic> {
        Ok(self.parse::<JsToml>()?.js.map(|js| js.input_path))
    }

    pub fn assets_output_dir(&self) -> Result<String, Diagnostic> {
        Ok(self.parse::<AssetsToml>()?.assets.output_dir)
    }

    pub fn assets_production_prefix(&self) -> Result<Option<String>, Diagnostic> {
        Ok(self.parse::<AssetsToml>()?.assets.production_prefix)
    }

    pub fn target(&self) -> Result<TargetLanguage, Diagnostic> {
        Ok(self.parse::<CompileToml>()?.compile.target)
    }

    pub fn output_path(&self) -> Result<String, Diagnostic> {
        Ok(self.parse::<CompileToml>()?.compile.output_path)
    }
}

#[derive(Debug, Clone, Deserialize)]
struct CssToml {
    css: Option<CssSection>,
}

#[derive(Debug, Clone, Deserialize)]
struct JsToml {
    js: Option<JsSection>,
}

#[derive(Debug, Clone, Deserialize)]
struct AssetsToml {
    assets: AssetsSection,
}

#[derive(Debug, Clone, Deserialize)]
struct CompileToml {
    compile: CompileSection,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct CompileSection {
    /// The language to build to: "ts" or "rust"
    target: TargetLanguage,

    /// The path to the file generated by hop build
    output_path: String,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct CssSection {
    /// Path to the CSS entrypoint, relative to the project root.
    #[serde(deserialize_with = "deserialize_document_id")]
    input_path: DocumentId,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct JsSection {
    /// Path to the JS/TS entrypoint, relative to the project root.
    #[serde(deserialize_with = "deserialize_document_id")]
    input_path: DocumentId,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct AssetsSection {
    /// When set, `asset!("/x")` rewrites to `"/{production_prefix}/x"` in `hop build`.
    /// Leading and trailing slashes are stripped before formatting.
    /// Empty strings are rejected, omit the field instead.
    #[serde(default, deserialize_with = "deserialize_production_prefix")]
    production_prefix: Option<String>,

    /// Directory to copy all `asset!()` referenced files into during `hop build`
    /// (relative to the project root). Absolute paths are rejected.
    #[serde(deserialize_with = "deserialize_output_dir")]
    output_dir: String,
}

fn deserialize_document_id<'de, D>(deserializer: D) -> Result<DocumentId, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let path = String::deserialize(deserializer)?;
    DocumentId::new(&path).map_err(serde::de::Error::custom)
}

fn deserialize_production_prefix<'de, D>(deserializer: D) -> Result<Option<String>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let production_prefix = String::deserialize(deserializer)?;
    if production_prefix.trim_matches('/').is_empty() {
        return Err(serde::de::Error::custom(
            "assets.production_prefix must be non-empty (omit the field to leave asset paths untouched)",
        ));
    }
    Ok(Some(production_prefix))
}

fn deserialize_output_dir<'de, D>(deserializer: D) -> Result<String, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let output_dir = String::deserialize(deserializer)?;
    if output_dir.starts_with('/') {
        return Err(serde::de::Error::custom(
            "assets.output_dir must be a relative path (must not start with '/')",
        ));
    }
    Ok(output_dir)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::document_annotator::DocumentAnnotator;
    use expect_test::expect;
    use indoc::indoc;

    fn from_toml(toml_str: &str) -> Config {
        Config::new(Document::new(
            DocumentId::new("hop.toml").unwrap(),
            toml_str.to_string(),
        ))
    }

    fn render(error: Diagnostic) -> String {
        DocumentAnnotator::new()
            .with_severity_label()
            .with_lines_before(1)
            .with_location()
            .annotate([error])
            .render()
    }

    #[test]
    fn accepts_config_with_typescript_target() {
        let toml_str = indoc! {r#"
            [compile]
            target = "ts"
            output_path = "app.ts"
        "#};
        let config = from_toml(toml_str);
        assert_eq!(config.target().unwrap(), TargetLanguage::Typescript);
        assert_eq!(config.output_path().unwrap(), "app.ts");
    }

    #[test]
    fn accepts_config_with_css_block() {
        let toml_str = indoc! {r#"
            [css]
            input_path = "styles/input.css"

            [compile]
            target = "ts"
            output_path = "app.ts"
        "#};
        let config = from_toml(toml_str);
        assert_eq!(
            config.css_input_path().unwrap(),
            Some(DocumentId::new("styles/input.css").unwrap())
        );
    }

    #[test]
    fn rejects_bundler_key_in_css_section() {
        let toml_str = indoc! {r#"
            [css]
            bundler = "tailwind_4"
            input_path = "styles/input.css"
        "#};
        expect![[r#"
            error: unknown field `bundler`, expected `input_path`
              --> hop.toml (line 2, col 1)
            1 | [css]
            2 | bundler = "tailwind_4"
              | ^^^^^^^
        "#]]
        .assert_eq(&render(from_toml(toml_str).css_input_path().unwrap_err()));
    }

    #[test]
    fn rejects_css_input_path_that_is_not_a_document_id() {
        let toml_str = indoc! {r#"
            [css]
            input_path = "../styles/input.css"
        "#};
        expect![[r#"
            error: Document ID cannot contain '.' or '..' components
              --> hop.toml (line 2, col 14)
            1 | [css]
            2 | input_path = "../styles/input.css"
              |              ^^^^^^^^^^^^^^^^^^^^^
        "#]]
        .assert_eq(&render(from_toml(toml_str).css_input_path().unwrap_err()));
    }

    #[test]
    fn rejects_css_block_missing_input_path() {
        let toml_str = indoc! {r#"
            [css]
        "#};
        expect![[r#"
            error: missing field `input_path`
              --> hop.toml (line 1, col 1)
            1 | [css]
              | ^^^^^
        "#]]
        .assert_eq(&render(from_toml(toml_str).css_input_path().unwrap_err()));
    }

    #[test]
    fn accepts_css_block_without_compile_section() {
        let toml_str = indoc! {r#"
            [css]
            input_path = "styles/input.css"
        "#};
        let config = from_toml(toml_str);
        assert_eq!(
            config.css_input_path().unwrap(),
            Some(DocumentId::new("styles/input.css").unwrap())
        );
    }

    #[test]
    fn accepts_config_with_js_block() {
        let toml_str = indoc! {r#"
            [js]
            input_path = "src/app.ts"

            [compile]
            target = "ts"
            output_path = "app.ts"
        "#};
        let config = from_toml(toml_str);
        assert_eq!(
            config.js_input_path().unwrap(),
            Some(DocumentId::new("src/app.ts").unwrap())
        );
    }

    #[test]
    fn rejects_bundler_key_in_js_section() {
        let toml_str = indoc! {r#"
            [js]
            bundler = "esbuild"
            input_path = "src/app.ts"
        "#};
        expect![[r#"
            error: unknown field `bundler`, expected `input_path`
              --> hop.toml (line 2, col 1)
            1 | [js]
            2 | bundler = "esbuild"
              | ^^^^^^^
        "#]]
        .assert_eq(&render(from_toml(toml_str).js_input_path().unwrap_err()));
    }

    #[test]
    fn rejects_absolute_js_input_path() {
        let toml_str = indoc! {r#"
            [js]
            input_path = "/src/app.ts"
        "#};
        expect![[r#"
            error: Document ID cannot start with '/'
              --> hop.toml (line 2, col 14)
            1 | [js]
            2 | input_path = "/src/app.ts"
              |              ^^^^^^^^^^^^^
        "#]]
        .assert_eq(&render(from_toml(toml_str).js_input_path().unwrap_err()));
    }

    #[test]
    fn rejects_js_block_missing_input_path() {
        let toml_str = indoc! {r#"
            [js]
        "#};
        expect![[r#"
            error: missing field `input_path`
              --> hop.toml (line 1, col 1)
            1 | [js]
              | ^^^^
        "#]]
        .assert_eq(&render(from_toml(toml_str).js_input_path().unwrap_err()));
    }

    #[test]
    fn rejects_config_with_unknown_field() {
        let toml_str = indoc! {r#"
            [compile]
            target = "ts"
            output_path = "app.ts"
            unknown_field = "should error"
        "#};
        expect![[r#"
            error: unknown field `unknown_field`, expected `target` or `output_path`
              --> hop.toml (line 4, col 1)
            3 | output_path = "app.ts"
            4 | unknown_field = "should error"
              | ^^^^^^^^^^^^^
        "#]]
        .assert_eq(&render(from_toml(toml_str).target().unwrap_err()));
    }

    #[test]
    fn rejects_config_with_invalid_target() {
        let toml_str = indoc! {r#"
            [compile]
            target = "invalid"
            output_path = "app.ts"
        "#};
        expect![[r#"
            error: unknown variant `invalid`, expected `ts` or `rust`
              --> hop.toml (line 2, col 10)
            1 | [compile]
            2 | target = "invalid"
              |          ^^^^^^^^^
        "#]]
        .assert_eq(&render(from_toml(toml_str).target().unwrap_err()));
    }

    #[test]
    fn accepts_all_valid_target_values() {
        let toml_str = indoc! {r#"
            [compile]
            target = "ts"
            output_path = "app.ts"
        "#};
        let config = from_toml(toml_str);
        assert_eq!(config.target().unwrap(), TargetLanguage::Typescript);

        let toml_str = indoc! {r#"
            [compile]
            target = "rust"
            output_path = "main.rs"
        "#};
        let config = from_toml(toml_str);
        assert_eq!(config.target().unwrap(), TargetLanguage::Rust);
    }

    #[test]
    fn rejects_full_target_names() {
        let toml_str = indoc! {r#"
            [compile]
            target = "typescript"
            output_path = "app.ts"
        "#};
        expect![[r#"
            error: unknown variant `typescript`, expected `ts` or `rust`
              --> hop.toml (line 2, col 10)
            1 | [compile]
            2 | target = "typescript"
              |          ^^^^^^^^^^^^
        "#]]
        .assert_eq(&render(from_toml(toml_str).target().unwrap_err()));
        let toml_str = indoc! {r#"
            [compile]
            target = "javascript"
            output_path = "app.js"
        "#};
        expect![[r#"
            error: unknown variant `javascript`, expected `ts` or `rust`
              --> hop.toml (line 2, col 10)
            1 | [compile]
            2 | target = "javascript"
              |          ^^^^^^^^^^^^
        "#]]
        .assert_eq(&render(from_toml(toml_str).target().unwrap_err()));
        let toml_str = indoc! {r#"
            [compile]
            target = "js"
            output_path = "app.js"
        "#};
        expect![[r#"
            error: unknown variant `js`, expected `ts` or `rust`
              --> hop.toml (line 2, col 10)
            1 | [compile]
            2 | target = "js"
              |          ^^^^
        "#]]
        .assert_eq(&render(from_toml(toml_str).target().unwrap_err()));
    }

    #[test]
    fn should_parse_config_without_build_section() {
        let toml_str = indoc! {r#"
        "#};
        let result = from_toml(toml_str).css_input_path();
        assert!(
            result.is_ok(),
            "Config without build section should parse: {:?}",
            result.err()
        );
    }

    #[test]
    fn should_parse_empty_config() {
        let toml_str = "";
        let result = from_toml(toml_str).css_input_path();
        assert!(
            result.is_ok(),
            "Empty config should parse: {:?}",
            result.err()
        );
    }

    #[test]
    fn rejects_compile_section_without_target() {
        let toml_str = indoc! {r#"
            [compile]
            output_path = "app.ts"
        "#};
        expect![[r#"
            error: missing field `target`
              --> hop.toml (line 1, col 1)
            1 | [compile]
              | ^^^^^^^^^
        "#]]
        .assert_eq(&render(from_toml(toml_str).target().unwrap_err()));
    }

    #[test]
    fn rejects_compile_section_without_output_path() {
        let toml_str = indoc! {r#"
            [compile]
            target = "ts"
        "#};
        expect![[r#"
            error: missing field `output_path`
              --> hop.toml (line 1, col 1)
            1 | [compile]
              | ^^^^^^^^^
        "#]]
        .assert_eq(&render(from_toml(toml_str).target().unwrap_err()));
    }

    #[test]
    fn rejects_missing_compile_section_when_required() {
        let toml_str = indoc! {r#"
        "#};
        expect![[r#"
            error: missing field `compile`
              --> hop.toml (line 1, col 1)
            1 |         
              | ^
        "#]]
        .assert_eq(&render(from_toml(toml_str).target().unwrap_err()));
    }

    #[test]
    fn ignores_incomplete_compile_section_when_reading_css() {
        let toml_str = indoc! {r#"
            [css]
            input_path = "styles/input.css"

            [compile]
            target = "ts"
        "#};
        let config = from_toml(toml_str);
        assert_eq!(
            config.css_input_path().unwrap(),
            Some(DocumentId::new("styles/input.css").unwrap())
        );
        expect!["missing field `output_path`"].assert_eq(config.target().unwrap_err().message());
    }

    #[test]
    fn ignores_unknown_top_level_sections() {
        let toml_str = indoc! {r#"
            [asset]
            output_dir = "dist/public"
        "#};
        let config = from_toml(toml_str);
        assert_eq!(config.css_input_path().unwrap(), None);
    }

    #[test]
    fn should_parse_assets_config_with_production_prefix() {
        let toml_str = indoc! {r#"
            [assets]
            production_prefix = "static/v1"
            output_dir = "dist/public"
        "#};
        let config = from_toml(toml_str);
        assert_eq!(
            config.assets_production_prefix().unwrap(),
            Some("static/v1".to_string())
        );
    }

    #[test]
    fn accepts_assets_section_without_production_prefix() {
        let toml_str = indoc! {r#"
            [assets]
            output_dir = "dist/public"
        "#};
        let config = from_toml(toml_str);
        assert!(config.assets_production_prefix().unwrap().is_none());
    }

    #[test]
    fn rejects_unknown_fields_in_assets_section() {
        let toml_str = indoc! {r#"
            [assets]
            production_prefix = "static/v1"
            output_dir = "dist/public"
            unknown_field = "should error"
        "#};
        expect![[r#"
            error: unknown field `unknown_field`, expected `production_prefix` or `output_dir`
              --> hop.toml (line 4, col 1)
            3 | output_dir = "dist/public"
            4 | unknown_field = "should error"
              | ^^^^^^^^^^^^^
        "#]]
        .assert_eq(&render(
            from_toml(toml_str).assets_output_dir().unwrap_err(),
        ));
    }

    #[test]
    fn rejects_empty_production_prefix() {
        let toml_str = indoc! {r#"
            [assets]
            production_prefix = ""
            output_dir = "dist/public"
        "#};
        expect![[r#"
            error: assets.production_prefix must be non-empty (omit the field to leave asset paths untouched)
              --> hop.toml (line 2, col 21)
            1 | [assets]
            2 | production_prefix = ""
              |                     ^^
        "#]].assert_eq(&render(from_toml(toml_str).assets_output_dir().unwrap_err()));
    }

    #[test]
    fn should_parse_assets_output_dir() {
        let toml_str = indoc! {r#"
            [assets]
            output_dir = "dist/public"
        "#};
        let config = from_toml(toml_str);
        assert_eq!(config.assets_output_dir().unwrap(), "dist/public");
    }

    #[test]
    fn rejects_missing_assets_section() {
        let toml_str = indoc! {r#"
            [compile]
            target = "ts"
            output_path = "app.ts"
        "#};
        expect![[r#"
            error: missing field `assets`
              --> hop.toml (line 1, col 1)
            1 | [compile]
              | ^
        "#]]
        .assert_eq(&render(
            from_toml(toml_str).assets_output_dir().unwrap_err(),
        ));
    }

    #[test]
    fn rejects_missing_output_dir() {
        let toml_str = indoc! {r#"
            [assets]
            production_prefix = "static/v1"
        "#};
        expect![[r#"
            error: missing field `output_dir`
              --> hop.toml (line 1, col 1)
            1 | [assets]
              | ^^^^^^^^
        "#]]
        .assert_eq(&render(
            from_toml(toml_str).assets_output_dir().unwrap_err(),
        ));
    }

    #[test]
    fn rejects_absolute_output_dir() {
        let toml_str = indoc! {r#"
            [assets]
            output_dir = "/absolute/path"
        "#};
        expect![[r#"
            error: assets.output_dir must be a relative path (must not start with '/')
              --> hop.toml (line 2, col 14)
            1 | [assets]
            2 | output_dir = "/absolute/path"
              |              ^^^^^^^^^^^^^^^^
        "#]]
        .assert_eq(&render(
            from_toml(toml_str).assets_output_dir().unwrap_err(),
        ));
    }

    #[test]
    fn accepts_nested_output_dir() {
        let toml_str = indoc! {r#"
            [assets]
            output_dir = "a/b/c"
        "#};
        let config = from_toml(toml_str);
        assert_eq!(config.assets_output_dir().unwrap(), "a/b/c");
    }

    #[test]
    fn accepts_dot_prefixed_output_dir() {
        let toml_str = indoc! {r#"
            [assets]
            output_dir = "./dist"
        "#};
        let config = from_toml(toml_str);
        assert_eq!(config.assets_output_dir().unwrap(), "./dist");
    }

    #[test]
    fn output_dir_and_production_prefix_can_coexist() {
        let toml_str = indoc! {r#"
            [assets]
            production_prefix = "static/v1"
            output_dir = "dist/public"
        "#};
        let config = from_toml(toml_str);
        assert_eq!(
            config.assets_production_prefix().unwrap(),
            Some("static/v1".to_string())
        );
        assert_eq!(config.assets_output_dir().unwrap(), "dist/public");
    }
}
