use serde::Deserialize;

/// The target language for compilation
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
pub enum TargetLanguage {
    #[serde(rename = "ts")]
    Typescript,
    #[serde(rename = "rust")]
    Rust,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HopConfig {
    #[serde(default)]
    pub css: Option<CssConfig>,

    /// JS configuration
    #[serde(default)]
    pub js: Option<JsConfig>,

    /// Compile configuration (optional - only needed for `hop build`)
    #[serde(default)]
    pub compile: CompileConfig,

    /// Asset configuration
    #[serde(default)]
    pub assets: Option<AssetsConfig>,
}

#[derive(Debug, Clone, Deserialize, Default)]
#[serde(deny_unknown_fields)]
pub struct CompileConfig {
    /// The language to build to: "ts" or "rust"
    pub target: Option<TargetLanguage>,

    /// The path to the file generated by hop build
    pub output_path: Option<String>,
}

/// The CSS bundler to use
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
pub enum CssBundler {
    #[serde(rename = "tailwind_4")]
    Tailwind4,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CssConfig {
    /// The CSS bundler. Currently only "tailwind_4" is supported.
    pub bundler: CssBundler,

    /// Path to the input CSS file
    pub input_path: String,
}

/// The JS bundler to use
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
pub enum JsBundler {
    #[serde(rename = "esbuild")]
    Esbuild,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JsConfig {
    /// The JS bundler. Currently only "esbuild" is supported.
    pub bundler: JsBundler,

    /// Path to the input JS/TS entrypoint file
    pub input_path: String,
}

#[derive(Debug, Clone)]
pub struct AssetsConfig {
    /// When set, `asset!("/x")` rewrites to `"/{production_prefix}/x"` in `hop build`.
    /// Leading and trailing slashes are stripped before formatting.
    /// Empty strings are rejected, omit the field instead.
    pub production_prefix: Option<String>,

    /// Directory to copy all `asset!()` referenced files into during `hop build`
    /// (relative to the project root). Absolute paths are rejected.
    pub output_dir: String,
}

impl<'de> serde::Deserialize<'de> for AssetsConfig {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        #[serde(deny_unknown_fields)]
        struct Helper {
            #[serde(default)]
            production_prefix: Option<String>,
            output_dir: Option<String>,
        }

        let helper = Helper::deserialize(deserializer)?;

        // Validate production_prefix
        if let Some(ref s) = helper.production_prefix {
            if s.trim_matches('/').is_empty() {
                return Err(serde::de::Error::custom(
                    "assets.production_prefix must be non-empty (omit the field to leave asset paths untouched)",
                ));
            }
        }

        // Require output_dir
        let output_dir = helper.output_dir.ok_or_else(|| {
            serde::de::Error::custom(
                "assets.output_dir is required (e.g. `output_dir = \"dist/public\"` in hop.toml)",
            )
        })?;

        // Validate output_dir is not absolute
        if output_dir.starts_with('/') {
            return Err(serde::de::Error::custom(
                "assets.output_dir must be a relative path (must not start with '/')",
            ));
        }

        Ok(AssetsConfig {
            production_prefix: helper.production_prefix,
            output_dir,
        })
    }
}

/// Resolved target configuration with all required fields validated
#[derive(Debug, Clone)]
pub struct ResolvedConfig {
    pub target: TargetLanguage,
    pub output_path: String,
}

#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    #[error("Missing 'compile.target' in hop.toml. Expected one of: \"ts\", \"rust\"")]
    MissingTarget,
    #[error("Missing 'compile.output_path' in hop.toml")]
    MissingOutputPath,
}

impl HopConfig {
    /// Parse HopConfig from a TOML string
    pub fn from_toml_str(toml_str: &str) -> anyhow::Result<Self> {
        let config: HopConfig = toml::from_str(toml_str)?;
        Ok(config)
    }

    /// Get the resolved config with all required build fields validated.
    /// Returns an error if `compile.target` or `compile.output_path` are missing.
    pub fn get_resolved_config(&self) -> Result<ResolvedConfig, ConfigError> {
        let target = self.compile.target.ok_or(ConfigError::MissingTarget)?;
        let output_path = self
            .compile
            .output_path
            .clone()
            .ok_or(ConfigError::MissingOutputPath)?;

        Ok(ResolvedConfig {
            target,
            output_path,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use indoc::indoc;

    #[test]
    fn should_accept_config_with_typescript_target() {
        let toml_str = indoc! {r#"
            [compile]
            target = "ts"
            output_path = "app.ts"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        assert_eq!(config.compile.target, Some(TargetLanguage::Typescript));
        assert_eq!(config.compile.output_path, Some("app.ts".to_string()));
    }

    #[test]
    fn should_accept_and_resolve_config_with_validated_fields() {
        let toml_str = indoc! {r#"
            [compile]
            target = "ts"
            output_path = "app.ts"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        let resolved = config.get_resolved_config().unwrap();
        assert_eq!(resolved.target, TargetLanguage::Typescript);
        assert_eq!(resolved.output_path, "app.ts");
    }

    #[test]
    fn should_accept_config_with_css_block() {
        let toml_str = indoc! {r#"
            [css]
            bundler = "tailwind_4"
            input_path = "styles/input.css"

            [compile]
            target = "ts"
            output_path = "app.ts"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        let css = config.css.unwrap();
        assert_eq!(css.bundler, CssBundler::Tailwind4);
        assert_eq!(css.input_path, "styles/input.css");
    }

    #[test]
    fn should_reject_unknown_css_bundler() {
        let toml_str = indoc! {r#"
            [css]
            bundler = "tailwind_3"
            input_path = "styles/input.css"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err());
    }

    #[test]
    fn should_reject_css_block_missing_bundler() {
        let toml_str = indoc! {r#"
            [css]
            input_path = "styles/input.css"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err());
    }

    #[test]
    fn should_reject_css_block_missing_input_path() {
        let toml_str = indoc! {r#"
            [css]
            bundler = "tailwind_4"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err());
    }

    #[test]
    fn should_accept_config_with_js_block() {
        let toml_str = indoc! {r#"
            [js]
            bundler = "esbuild"
            input_path = "src/app.ts"

            [compile]
            target = "ts"
            output_path = "app.ts"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        let js = config.js.unwrap();
        assert_eq!(js.bundler, JsBundler::Esbuild);
        assert_eq!(js.input_path, "src/app.ts");
    }

    #[test]
    fn should_reject_unknown_js_bundler() {
        let toml_str = indoc! {r#"
            [js]
            bundler = "webpack"
            input_path = "src/app.ts"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err());
    }

    #[test]
    fn should_reject_js_block_missing_bundler() {
        let toml_str = indoc! {r#"
            [js]
            input_path = "src/app.ts"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err());
    }

    #[test]
    fn should_reject_js_block_missing_input_path() {
        let toml_str = indoc! {r#"
            [js]
            bundler = "esbuild"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err());
    }

    #[test]
    fn should_reject_config_with_unknown_field() {
        let toml_str = indoc! {r#"
            [compile]
            target = "ts"
            output_path = "app.ts"
            unknown_field = "should error"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err());
        let error_msg = result.unwrap_err().to_string();
        assert!(error_msg.contains("unknown_field"));
    }

    #[test]
    fn should_reject_config_with_invalid_target() {
        let toml_str = indoc! {r#"
            [compile]
            target = "invalid"
            output_path = "app.ts"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err());
    }

    #[test]
    fn should_accept_all_valid_target_values() {
        // Test "ts"
        let toml_str = indoc! {r#"
            [compile]
            target = "ts"
            output_path = "app.ts"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        assert_eq!(config.compile.target, Some(TargetLanguage::Typescript));

        // Test "rust"
        let toml_str = indoc! {r#"
            [compile]
            target = "rust"
            output_path = "main.rs"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        assert_eq!(config.compile.target, Some(TargetLanguage::Rust));
    }

    #[test]
    fn should_reject_full_target_names() {
        // "typescript" should be rejected (only "ts" is valid)
        let toml_str = indoc! {r#"
            [compile]
            target = "typescript"
            output_path = "app.ts"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err());

        // "javascript" should be rejected (it's no longer a valid target)
        let toml_str = indoc! {r#"
            [compile]
            target = "javascript"
            output_path = "app.js"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err());

        // "js" should be rejected (it's no longer a valid target)
        let toml_str = indoc! {r#"
            [compile]
            target = "js"
            output_path = "app.js"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err());
    }

    #[test]
    fn should_parse_config_without_build_section() {
        let toml_str = indoc! {r#"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(
            result.is_ok(),
            "Config without build section should parse: {:?}",
            result.err()
        );
    }

    #[test]
    fn should_parse_empty_config() {
        let toml_str = "";
        let result = HopConfig::from_toml_str(toml_str);
        assert!(
            result.is_ok(),
            "Empty config should parse: {:?}",
            result.err()
        );
    }

    #[test]
    fn get_resolved_config_should_error_on_missing_target() {
        let toml_str = indoc! {r#"
            [compile]
            output_path = "app.ts"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        let result = config.get_resolved_config();
        assert!(result.is_err());
        let err_msg = result.unwrap_err().to_string();
        assert!(err_msg.contains("compile.target"));
        assert!(err_msg.contains("hop.toml"));
    }

    #[test]
    fn get_resolved_config_should_error_on_missing_output_path() {
        let toml_str = indoc! {r#"
            [compile]
            target = "ts"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        let result = config.get_resolved_config();
        assert!(result.is_err());
        let err_msg = result.unwrap_err().to_string();
        assert!(err_msg.contains("compile.output_path"));
        assert!(err_msg.contains("hop.toml"));
    }

    #[test]
    fn get_resolved_config_should_error_when_no_build_section() {
        let toml_str = indoc! {r#"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        let result = config.get_resolved_config();
        assert!(result.is_err());
    }

    // Assets config tests

    #[test]
    fn should_parse_assets_config_with_production_prefix() {
        let toml_str = indoc! {r#"
            [assets]
            production_prefix = "static/v1"
            output_dir = "dist/public"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        let assets = config.assets.as_ref().unwrap();
        assert_eq!(assets.production_prefix, Some("static/v1".to_string()));
    }

    #[test]
    fn should_allow_empty_config_without_assets() {
        let toml_str = "";
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        assert!(config.assets.is_none());
    }

    #[test]
    fn should_reject_unknown_fields_in_assets_section() {
        let toml_str = indoc! {r#"
            [assets]
            production_prefix = "static/v1"
            output_dir = "dist/public"
            unknown_field = "should error"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err());
        let error_msg = result.unwrap_err().to_string();
        assert!(error_msg.contains("unknown_field"));
    }

    #[test]
    fn should_reject_empty_production_prefix() {
        let toml_str = indoc! {r#"
            [assets]
            production_prefix = ""
            output_dir = "dist/public"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err(), "Expected empty prefix to be rejected");
    }

    // assets.output_dir tests

    #[test]
    fn should_parse_assets_output_dir() {
        let toml_str = indoc! {r#"
            [assets]
            output_dir = "dist/public"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        let assets = config.assets.as_ref().unwrap();
        assert_eq!(assets.output_dir, "dist/public".to_string());
    }

    #[test]
    fn should_reject_missing_output_dir() {
        let toml_str = indoc! {r#"
            [assets]
            production_prefix = "static/v1"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(
            result.is_err(),
            "Expected missing output_dir to be rejected"
        );
        let error_msg = result.unwrap_err().to_string();
        assert!(
            error_msg.contains("output_dir"),
            "Error should mention output_dir: {}",
            error_msg
        );
        assert!(
            error_msg.contains("dist/public"),
            "Error should include example value: {}",
            error_msg
        );
    }

    #[test]
    fn should_reject_absolute_output_dir() {
        let toml_str = indoc! {r#"
            [assets]
            output_dir = "/absolute/path"
        "#};
        let result = HopConfig::from_toml_str(toml_str);
        assert!(result.is_err(), "Expected absolute path to be rejected");
        let error_msg = result.unwrap_err().to_string();
        assert!(error_msg.contains("output_dir"));
    }

    #[test]
    fn should_accept_nested_output_dir() {
        let toml_str = indoc! {r#"
            [assets]
            output_dir = "a/b/c"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        let assets = config.assets.as_ref().unwrap();
        assert_eq!(assets.output_dir, "a/b/c".to_string());
    }

    #[test]
    fn should_accept_dot_prefixed_output_dir() {
        let toml_str = indoc! {r#"
            [assets]
            output_dir = "./dist"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        let assets = config.assets.as_ref().unwrap();
        assert_eq!(assets.output_dir, "./dist".to_string());
    }

    #[test]
    fn output_dir_and_production_prefix_can_coexist() {
        let toml_str = indoc! {r#"
            [assets]
            production_prefix = "static/v1"
            output_dir = "dist/public"
        "#};
        let config = HopConfig::from_toml_str(toml_str).unwrap();
        let assets = config.assets.as_ref().unwrap();
        assert_eq!(assets.production_prefix, Some("static/v1".to_string()));
        assert_eq!(assets.output_dir, "dist/public".to_string());
    }
}
