use crate::document::CheapString;

/// Escape HTML special characters to prevent XSS
/// Converts &, <, >, ", and ' to their HTML entity equivalents
pub fn write_escaped_html(text: &str, output: &mut String) {
    for c in text.chars() {
        match c {
            '&' => output.push_str("&amp;"),
            '<' => output.push_str("&lt;"),
            '>' => output.push_str("&gt;"),
            '"' => output.push_str("&quot;"),
            '\'' => output.push_str("&#39;"),
            _ => output.push(c),
        }
    }
}

/// Return true if the string represents a void element.
/// See https://developer.mozilla.org/en-US/docs/Glossary/Void_element
pub fn is_void_element(tag_name: &str) -> bool {
    matches!(
        tag_name,
        "area"
            | "base"
            | "br"
            | "col"
            | "embed"
            | "hr"
            | "img"
            | "input"
            | "link"
            | "meta"
            | "source"
            | "track"
            | "wbr"
    )
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum HtmlElement {
    Html,
    Base,
    Head,
    Link,
    Meta,
    Style,
    Title,
    Body,
    Address,
    Article,
    Aside,
    Footer,
    Header,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    Hgroup,
    Main,
    Nav,
    Section,
    Search,
    Blockquote,
    Dd,
    Div,
    Dl,
    Dt,
    Figcaption,
    Figure,
    Hr,
    Li,
    Menu,
    Ol,
    P,
    Pre,
    Ul,
    A,
    Abbr,
    B,
    Bdi,
    Bdo,
    Br,
    Cite,
    Code,
    Data,
    Dfn,
    Em,
    I,
    Kbd,
    Mark,
    Q,
    Rp,
    Rt,
    Ruby,
    S,
    Samp,
    Small,
    Span,
    Strong,
    Sub,
    Sup,
    Time,
    U,
    Var,
    Wbr,
    Area,
    Audio,
    Img,
    Map,
    Track,
    Video,
    Embed,
    Iframe,
    Object,
    Picture,
    Source,
    Canvas,
    Noscript,
    Script,
    Del,
    Ins,
    Caption,
    Col,
    Colgroup,
    Table,
    Tbody,
    Td,
    Tfoot,
    Th,
    Thead,
    Tr,
    Button,
    Datalist,
    Fieldset,
    Form,
    Input,
    Label,
    Legend,
    Meter,
    Optgroup,
    Option,
    Output,
    Progress,
    Select,
    Textarea,
    Details,
    Dialog,
    Summary,
    Slot,
    Template,
    Svg,
    G,
    Path,
    Circle,
    Rect,
    Line,
    Polygon,
    Polyline,
    Ellipse,
    Defs,
    Use,
    Symbol,
    Desc,
    Marker,
    Mask,
    Pattern,
    Stop,
    Switch,
    Text,
    Tspan,
    Image,
    View,
    Animate,
    Set,
    Mpath,
    Metadata,
    Filter,
    Custom(CheapString),
}

impl HtmlElement {
    pub fn as_str(&self) -> &str {
        match self {
            HtmlElement::Html => "html",
            HtmlElement::Base => "base",
            HtmlElement::Head => "head",
            HtmlElement::Link => "link",
            HtmlElement::Meta => "meta",
            HtmlElement::Style => "style",
            HtmlElement::Title => "title",
            HtmlElement::Body => "body",
            HtmlElement::Address => "address",
            HtmlElement::Article => "article",
            HtmlElement::Aside => "aside",
            HtmlElement::Footer => "footer",
            HtmlElement::Header => "header",
            HtmlElement::H1 => "h1",
            HtmlElement::H2 => "h2",
            HtmlElement::H3 => "h3",
            HtmlElement::H4 => "h4",
            HtmlElement::H5 => "h5",
            HtmlElement::H6 => "h6",
            HtmlElement::Hgroup => "hgroup",
            HtmlElement::Main => "main",
            HtmlElement::Nav => "nav",
            HtmlElement::Section => "section",
            HtmlElement::Search => "search",
            HtmlElement::Blockquote => "blockquote",
            HtmlElement::Dd => "dd",
            HtmlElement::Div => "div",
            HtmlElement::Dl => "dl",
            HtmlElement::Dt => "dt",
            HtmlElement::Figcaption => "figcaption",
            HtmlElement::Figure => "figure",
            HtmlElement::Hr => "hr",
            HtmlElement::Li => "li",
            HtmlElement::Menu => "menu",
            HtmlElement::Ol => "ol",
            HtmlElement::P => "p",
            HtmlElement::Pre => "pre",
            HtmlElement::Ul => "ul",
            HtmlElement::A => "a",
            HtmlElement::Abbr => "abbr",
            HtmlElement::B => "b",
            HtmlElement::Bdi => "bdi",
            HtmlElement::Bdo => "bdo",
            HtmlElement::Br => "br",
            HtmlElement::Cite => "cite",
            HtmlElement::Code => "code",
            HtmlElement::Data => "data",
            HtmlElement::Dfn => "dfn",
            HtmlElement::Em => "em",
            HtmlElement::I => "i",
            HtmlElement::Kbd => "kbd",
            HtmlElement::Mark => "mark",
            HtmlElement::Q => "q",
            HtmlElement::Rp => "rp",
            HtmlElement::Rt => "rt",
            HtmlElement::Ruby => "ruby",
            HtmlElement::S => "s",
            HtmlElement::Samp => "samp",
            HtmlElement::Small => "small",
            HtmlElement::Span => "span",
            HtmlElement::Strong => "strong",
            HtmlElement::Sub => "sub",
            HtmlElement::Sup => "sup",
            HtmlElement::Time => "time",
            HtmlElement::U => "u",
            HtmlElement::Var => "var",
            HtmlElement::Wbr => "wbr",
            HtmlElement::Area => "area",
            HtmlElement::Audio => "audio",
            HtmlElement::Img => "img",
            HtmlElement::Map => "map",
            HtmlElement::Track => "track",
            HtmlElement::Video => "video",
            HtmlElement::Embed => "embed",
            HtmlElement::Iframe => "iframe",
            HtmlElement::Object => "object",
            HtmlElement::Picture => "picture",
            HtmlElement::Source => "source",
            HtmlElement::Canvas => "canvas",
            HtmlElement::Noscript => "noscript",
            HtmlElement::Script => "script",
            HtmlElement::Del => "del",
            HtmlElement::Ins => "ins",
            HtmlElement::Caption => "caption",
            HtmlElement::Col => "col",
            HtmlElement::Colgroup => "colgroup",
            HtmlElement::Table => "table",
            HtmlElement::Tbody => "tbody",
            HtmlElement::Td => "td",
            HtmlElement::Tfoot => "tfoot",
            HtmlElement::Th => "th",
            HtmlElement::Thead => "thead",
            HtmlElement::Tr => "tr",
            HtmlElement::Button => "button",
            HtmlElement::Datalist => "datalist",
            HtmlElement::Fieldset => "fieldset",
            HtmlElement::Form => "form",
            HtmlElement::Input => "input",
            HtmlElement::Label => "label",
            HtmlElement::Legend => "legend",
            HtmlElement::Meter => "meter",
            HtmlElement::Optgroup => "optgroup",
            HtmlElement::Option => "option",
            HtmlElement::Output => "output",
            HtmlElement::Progress => "progress",
            HtmlElement::Select => "select",
            HtmlElement::Textarea => "textarea",
            HtmlElement::Details => "details",
            HtmlElement::Dialog => "dialog",
            HtmlElement::Summary => "summary",
            HtmlElement::Slot => "slot",
            HtmlElement::Template => "template",
            HtmlElement::Svg => "svg",
            HtmlElement::G => "g",
            HtmlElement::Path => "path",
            HtmlElement::Circle => "circle",
            HtmlElement::Rect => "rect",
            HtmlElement::Line => "line",
            HtmlElement::Polygon => "polygon",
            HtmlElement::Polyline => "polyline",
            HtmlElement::Ellipse => "ellipse",
            HtmlElement::Defs => "defs",
            HtmlElement::Use => "use",
            HtmlElement::Symbol => "symbol",
            HtmlElement::Desc => "desc",
            HtmlElement::Marker => "marker",
            HtmlElement::Mask => "mask",
            HtmlElement::Pattern => "pattern",
            HtmlElement::Stop => "stop",
            HtmlElement::Switch => "switch",
            HtmlElement::Text => "text",
            HtmlElement::Tspan => "tspan",
            HtmlElement::Image => "image",
            HtmlElement::View => "view",
            HtmlElement::Animate => "animate",
            HtmlElement::Set => "set",
            HtmlElement::Mpath => "mpath",
            HtmlElement::Metadata => "metadata",
            HtmlElement::Filter => "filter",
            HtmlElement::Custom(s) => s.as_str(),
        }
    }

    fn known(name: &str) -> Option<HtmlElement> {
        let element = match name {
            "html" => HtmlElement::Html,
            "base" => HtmlElement::Base,
            "head" => HtmlElement::Head,
            "link" => HtmlElement::Link,
            "meta" => HtmlElement::Meta,
            "style" => HtmlElement::Style,
            "title" => HtmlElement::Title,
            "body" => HtmlElement::Body,
            "address" => HtmlElement::Address,
            "article" => HtmlElement::Article,
            "aside" => HtmlElement::Aside,
            "footer" => HtmlElement::Footer,
            "header" => HtmlElement::Header,
            "h1" => HtmlElement::H1,
            "h2" => HtmlElement::H2,
            "h3" => HtmlElement::H3,
            "h4" => HtmlElement::H4,
            "h5" => HtmlElement::H5,
            "h6" => HtmlElement::H6,
            "hgroup" => HtmlElement::Hgroup,
            "main" => HtmlElement::Main,
            "nav" => HtmlElement::Nav,
            "section" => HtmlElement::Section,
            "search" => HtmlElement::Search,
            "blockquote" => HtmlElement::Blockquote,
            "dd" => HtmlElement::Dd,
            "div" => HtmlElement::Div,
            "dl" => HtmlElement::Dl,
            "dt" => HtmlElement::Dt,
            "figcaption" => HtmlElement::Figcaption,
            "figure" => HtmlElement::Figure,
            "hr" => HtmlElement::Hr,
            "li" => HtmlElement::Li,
            "menu" => HtmlElement::Menu,
            "ol" => HtmlElement::Ol,
            "p" => HtmlElement::P,
            "pre" => HtmlElement::Pre,
            "ul" => HtmlElement::Ul,
            "a" => HtmlElement::A,
            "abbr" => HtmlElement::Abbr,
            "b" => HtmlElement::B,
            "bdi" => HtmlElement::Bdi,
            "bdo" => HtmlElement::Bdo,
            "br" => HtmlElement::Br,
            "cite" => HtmlElement::Cite,
            "code" => HtmlElement::Code,
            "data" => HtmlElement::Data,
            "dfn" => HtmlElement::Dfn,
            "em" => HtmlElement::Em,
            "i" => HtmlElement::I,
            "kbd" => HtmlElement::Kbd,
            "mark" => HtmlElement::Mark,
            "q" => HtmlElement::Q,
            "rp" => HtmlElement::Rp,
            "rt" => HtmlElement::Rt,
            "ruby" => HtmlElement::Ruby,
            "s" => HtmlElement::S,
            "samp" => HtmlElement::Samp,
            "small" => HtmlElement::Small,
            "span" => HtmlElement::Span,
            "strong" => HtmlElement::Strong,
            "sub" => HtmlElement::Sub,
            "sup" => HtmlElement::Sup,
            "time" => HtmlElement::Time,
            "u" => HtmlElement::U,
            "var" => HtmlElement::Var,
            "wbr" => HtmlElement::Wbr,
            "area" => HtmlElement::Area,
            "audio" => HtmlElement::Audio,
            "img" => HtmlElement::Img,
            "map" => HtmlElement::Map,
            "track" => HtmlElement::Track,
            "video" => HtmlElement::Video,
            "embed" => HtmlElement::Embed,
            "iframe" => HtmlElement::Iframe,
            "object" => HtmlElement::Object,
            "picture" => HtmlElement::Picture,
            "source" => HtmlElement::Source,
            "canvas" => HtmlElement::Canvas,
            "noscript" => HtmlElement::Noscript,
            "script" => HtmlElement::Script,
            "del" => HtmlElement::Del,
            "ins" => HtmlElement::Ins,
            "caption" => HtmlElement::Caption,
            "col" => HtmlElement::Col,
            "colgroup" => HtmlElement::Colgroup,
            "table" => HtmlElement::Table,
            "tbody" => HtmlElement::Tbody,
            "td" => HtmlElement::Td,
            "tfoot" => HtmlElement::Tfoot,
            "th" => HtmlElement::Th,
            "thead" => HtmlElement::Thead,
            "tr" => HtmlElement::Tr,
            "button" => HtmlElement::Button,
            "datalist" => HtmlElement::Datalist,
            "fieldset" => HtmlElement::Fieldset,
            "form" => HtmlElement::Form,
            "input" => HtmlElement::Input,
            "label" => HtmlElement::Label,
            "legend" => HtmlElement::Legend,
            "meter" => HtmlElement::Meter,
            "optgroup" => HtmlElement::Optgroup,
            "option" => HtmlElement::Option,
            "output" => HtmlElement::Output,
            "progress" => HtmlElement::Progress,
            "select" => HtmlElement::Select,
            "textarea" => HtmlElement::Textarea,
            "details" => HtmlElement::Details,
            "dialog" => HtmlElement::Dialog,
            "summary" => HtmlElement::Summary,
            "slot" => HtmlElement::Slot,
            "template" => HtmlElement::Template,
            "svg" => HtmlElement::Svg,
            "g" => HtmlElement::G,
            "path" => HtmlElement::Path,
            "circle" => HtmlElement::Circle,
            "rect" => HtmlElement::Rect,
            "line" => HtmlElement::Line,
            "polygon" => HtmlElement::Polygon,
            "polyline" => HtmlElement::Polyline,
            "ellipse" => HtmlElement::Ellipse,
            "defs" => HtmlElement::Defs,
            "use" => HtmlElement::Use,
            "symbol" => HtmlElement::Symbol,
            "desc" => HtmlElement::Desc,
            "marker" => HtmlElement::Marker,
            "mask" => HtmlElement::Mask,
            "pattern" => HtmlElement::Pattern,
            "stop" => HtmlElement::Stop,
            "switch" => HtmlElement::Switch,
            "text" => HtmlElement::Text,
            "tspan" => HtmlElement::Tspan,
            "image" => HtmlElement::Image,
            "view" => HtmlElement::View,
            "animate" => HtmlElement::Animate,
            "set" => HtmlElement::Set,
            "mpath" => HtmlElement::Mpath,
            "metadata" => HtmlElement::Metadata,
            "filter" => HtmlElement::Filter,
            _ => return None,
        };
        Some(element)
    }

    pub fn is_void(&self) -> bool {
        is_void_element(self.as_str())
    }

    pub fn parse(name: &str) -> Option<HtmlElement> {
        if let Some(el) = Self::known(name) {
            Some(el)
        } else if name.contains('-') {
            Some(HtmlElement::Custom(CheapString::new(name.to_string())))
        } else {
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classifies_known_html_element() {
        let el = HtmlElement::parse("div").unwrap();
        assert_eq!(el, HtmlElement::Div);
        assert_eq!(el.as_str(), "div");
    }

    #[test]
    fn classifies_known_svg_element() {
        assert_eq!(HtmlElement::parse("path"), Some(HtmlElement::Path));
    }

    #[test]
    fn classifies_hyphenated_custom_element() {
        let el = HtmlElement::parse("my-widget").unwrap();
        assert_eq!(
            el,
            HtmlElement::Custom(CheapString::new("my-widget".to_string()))
        );
        assert_eq!(el.as_str(), "my-widget");
    }

    #[test]
    fn rejects_unknown_bare_name() {
        assert_eq!(HtmlElement::parse("dvi"), None);
    }

    #[test]
    fn rejects_mathml() {
        assert_eq!(HtmlElement::parse("math"), None);
    }

    #[test]
    fn void_element_check_matches_helper() {
        assert!(HtmlElement::parse("br").unwrap().is_void());
        assert!(!HtmlElement::parse("div").unwrap().is_void());
        assert!(!HtmlElement::parse("my-widget").unwrap().is_void());
    }
}
