mod eliminate_unused_variable_declarations;
mod normalize_fragments;
mod perform_partial_evaluation;

pub use eliminate_unused_variable_declarations::eliminate_unused_variable_declarations;
pub use normalize_fragments::normalize_fragments;
pub use perform_partial_evaluation::perform_partial_evaluation;
