/// Lowercase names that are reserved. Applies to variable names, field names
/// and module name components.
///
/// Most of these names are keywords recognized by the tokenizer or reserved
/// for future use as keywords.
///
/// One exception is `constructor` which breaks the TS transpiler if used
/// as a field name.
pub(super) fn is_reserved_name(name: &str) -> bool {
    matches!(
        name,
        "alias"
            | "and"
            | "as"
            | "assert"
            | "async"
            | "auto"
            | "await"
            | "break"
            | "case"
            | "catch"
            | "comp"
            | "component"
            | "const"
            | "constructor"
            | "continue"
            | "default"
            | "defer"
            | "elif"
            | "else"
            | "entrypoint"
            | "enum"
            | "export"
            | "extends"
            | "false"
            | "final"
            | "finally"
            | "fn"
            | "from"
            | "func"
            | "get"
            | "if"
            | "impl"
            | "implements"
            | "import"
            | "in"
            | "include"
            | "interface"
            | "internal"
            | "is"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "mut"
            | "namespace"
            | "new"
            | "newtype"
            | "nil"
            | "not"
            | "null"
            | "of"
            | "or"
            | "out"
            | "package"
            | "page"
            | "priv"
            | "private"
            | "pub"
            | "public"
            | "record"
            | "return"
            | "self"
            | "set"
            | "static"
            | "struct"
            | "super"
            | "this"
            | "throw"
            | "trait"
            | "true"
            | "try"
            | "undefined"
            | "use"
            | "val"
            | "var"
            | "view"
            | "void"
            | "when"
            | "where"
            | "while"
            | "yield"
    )
}

/// Type names that are reserved.
///
/// Most of these names are built-in type names recognized by the tokenizer or
/// reserved for future use. Exceptions are `Box` and
/// `Vec` which are emitted unqualified by the Rust transpiler. These could be
/// unreserved in the future by using qualified names in the transpiler.
///
/// A special case is the type name `View` which is reserved since a trait of
/// the name View is part of the public interface emitted by the Rust
/// transpiler.
pub(super) fn is_reserved_type_name(name: &str) -> bool {
    matches!(
        name,
        "Any"
            | "Arr"
            | "Array"
            | "Async"
            | "Auto"
            | "Bool"
            | "Box"
            | "CSS"
            | "Class"
            | "Classes"
            | "Client"
            | "Comp"
            | "Computed"
            | "Dyn"
            | "Dynamic"
            | "Enum"
            | "Err"
            | "Error"
            | "Float"
            | "Fn"
            | "Fragment"
            | "Func"
            | "Function"
            | "Future"
            | "HTML"
            | "IO"
            | "Int"
            | "List"
            | "Map"
            | "Never"
            | "None"
            | "Object"
            | "Ok"
            | "Option"
            | "Promise"
            | "Rec"
            | "Record"
            | "Result"
            | "Runtime"
            | "Safe"
            | "Scope"
            | "Scoped"
            | "Self"
            | "Set"
            | "Some"
            | "Static"
            | "String"
            | "Struct"
            | "Task"
            | "Trusted"
            | "Tuple"
            | "Type"
            | "Union"
            | "Unknown"
            | "Vec"
            | "View"
            | "Void"
    )
}
